=== EmericJdt/ITtraining/Improved_BigBang/BigBang.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- les balises isolées (simples) -->
  <xsd:element name="name" type="xsd:string"/>
  <xsd:element name="maxCapacity" type="xsd:int"/>
  <xsd:element name="delay" type="xsd:int"/>
  <xsd:element name="effeciency" type="xsd:double"/>
  <xsd:element name="entitiesNumber" type="xsd:int"/>
  <xsd:element name="populationNumber" type="xsd:double"/>
  <xsd:element name="superDepression" type="xsd:double"/>
  <xsd:element name="naturalCatastroph" type="xsd:double"/>
  <xsd:element name="superGrowth" type="xsd:double"/>
  <xsd:element name="funds" type="xsd:double"/>
  <xsd:element name="costs" type="xsd:double"/>
  <xsd:element name="fees" type="xsd:double"/>
  <xsd:element name="potential" type="xsd:int"/>
  <!-- les balises isolées (simples) -->

  <!-- les balises isolées (complexes) -->
  <xsd:element name="mainAccount">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="fees" type="xsd:double"/>
          <xsd:attribute name="currency" type="xsd:string"/>
          <xsd:attribute name="amount" type="xsd:double"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
    <!-- les balises isolées (complexes) -->

  <!-- sous-balises (complexes) de <Régions> -->
  <xsd:element name="demographie">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="populationNumber"/>
        <xsd:element name="PIB">
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="currency" type="xsd:string"/>
                <xsd:attribute name="amount" type="xsd:double"/>
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="economyPotential">
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="currency" type="xsd:string"/>
                <xsd:attribute name="amount" type="xsd:double"/>
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="macroEventProba">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="superDepression"/>
        <xsd:element ref="naturalCatastroph"/>
        <xsd:element ref="superGrowth"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- sous-balises (complexes) de <Régions> -->

  <!-- sous-balises (complexes) de <Corporation> -->
  <xsd:element name="technologiesList">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="technology">
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="xsd:string"/>
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="shops">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="shop">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="maxCapacity"/>
            </xsd:sequence>
            <xsd:attribute name="location" type="xsd:string"/>
            <xsd:attribute name="ID" type="xsd:double"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="RDCenters">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="RDCenter">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="technologiesList"/>
              <xsd:element ref="funds"/>
              <xsd:element ref="costs"/>
              <xsd:element ref="delay"/>
            </xsd:sequence>
            <xsd:attribute name="ID" type="xsd:double"/>
          </xsd:complexType>
        </xsd:element>     
      </xsd:sequence>
      <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="factories">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="factory">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="maxCapacity"/>
              <xsd:element ref="effeciency"/>
            </xsd:sequence>
            <xsd:attribute name="ID" type="xsd:double"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="entities">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="shops"/>
        <xsd:element ref="RDCenters"/>
        <xsd:element ref="factories"/>
      </xsd:sequence>
      <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>
  <!-- sous-balises (complexes) de <Corporation> -->

  <!-- <Region> -->
  <xsd:element name="Region">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name"/>
        <xsd:element ref="demographie"/>
        <xsd:element ref="macroEventProba"/>
        <xsd:element ref="entitiesNumber"/>
      </xsd:sequence>
      <xsd:attribute name="number" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>
  <!-- <Region> -->

  <!-- <Corporation> -->
  <xsd:element name="Corporation">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name"/>
        <xsd:element ref="entities"/>
        <xsd:element ref="mainAccount"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- <Corporation> -->

  <!-- <Bank> -->
  <xsd:element name="Bank">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="mainAccount"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- <Bank> -->
  
  <!--> Transports -->
  <xsd:element name="Transports">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="type">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="maritime"/>
                <xsd:enumeration value="rail"/>
                <xsd:enumeration value="air"/>
                <xsd:enumeration value="road"/>
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <!--> Transports -->
  
  <!-- <TimeStamp> -->
  <xsd:element name="TimeStamp">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="maxQuarter" type="xsd:int"/>
        <xsd:element name="delay"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- <TimeStamp> -->

  <!-- <refcost>-->
  <xsd:element name="refcost">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:double">
          <xsd:attribute name="id" type="xsd:int"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <!-- <refcost>-->
  
  <!-- <product> -->
  <xsd:element name="product">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name"/>
        <xsd:element name="potential"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
        <xsd:element name="refcost"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>
  <!-- <product> -->

  <!-- <Global> -->
  <xsd:element name="Global">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="product"/>
        <xsd:element name="product"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- <Global> -->

  <!-- <World> -->
  <xsd:element name="World">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Region"/>
        <xsd:element ref="Corporation"/>
        <xsd:element ref="Bank"/>
        <xsd:element ref="TimeStamp"/>
        <xsd:element ref="Transports"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- <World> -->

</xsd:schema>

=== EmericJdt/ITtraining/Improved_BigBang/teachTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- le fichier entrée du jeu -->
<!-- il nous faut les balises des différentes classes principales -->
<World xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BigBang.xsd">

	<Region id="1">
		<name>USA</name>
		<demographie>
			<populationNumber>300</populationNumber>
			<PIB currency="$">18570</PIB>
			<economyPotential currency="$">5</economyPotential>
		</demographie>
		<macroEventProba>
			<superDepression>0.10</superDepression>
			<naturalCatastroph>0.10</naturalCatastroph>
			<superGrowth>0.02</superGrowth>
		</macroEventProba>
		<entitiesNumber>1000</entitiesNumber>
	</Region>
	<Region id="2">
		<name>UE</name>
		<demographie>
			<populationNumber>500</populationNumber>
			<PIB currency="$">18412</PIB>
			<economyPotential currency="$">7</economyPotential>
		</demographie>
		<macroEventProba>
			<superDepression>0.05</superDepression>
			<naturalCatastroph>0.01</naturalCatastroph>
			<superGrowth>0.01</superGrowth>
		</macroEventProba>
		<entitiesNumber>1000</entitiesNumber>
	</Region>	
	<Region id="3">
		<name>JP</name>
		<demographie>
			<populationNumber>130</populationNumber>
			<PIB currency="">4000</PIB>
			<economyPotential currency="$">2</economyPotential>
		</demographie>
		<macroEventProba>
			<superDepression>0.2</superDepression>
			<naturalCatastroph>0.2</naturalCatastroph>
			<superGrowth>0.01</superGrowth>
		</macroEventProba>
		<entitiesNumber>100</entitiesNumber>
	</Region>
	<Corporation id ="1">
		<name>APPEL</name>
		<entities number="0">
	        <shops number="0">
	          <shop location="" ID="">
	            <maxCapacity></maxCapacity>      <!-- la capacité max de stockage qu'elle peut avoir -->
	          </shop>
	        </shops>
				<RDCenters number="">
					<RDCenter ID="">
            <technologiesList>
              <technology type="older/current/newer"></technology>
            </technologiesList>
            <funds></funds>
            <costs></costs>
						<delay></delay><!-- le temps minimum accordé apres une découverte (face aux autres joueurs) -->
					</RDCenter>
				</RDCenters>
				<factories number="">
					<factory ID="">
						<maxCapacity>"à remplir</maxCapacity><!-- le stock max qu'elle peut avoir a dispo -->
						<effeciency>"à remplir"</effeciency>
					</factory>
				</factories>
			</entities>
			<mainAccount currency="$" fees="" amount="50000000"></mainAccount>
	</Corporation>
<Corporation id ="2">
		<name></name>
		<entities number="">
	        <shops number="">
	          <shop location="" ID="">
	            <maxCapacity></maxCapacity>      <!-- la capacité max de stockage qu'elle peut avoir -->
	          </shop>
	        </shops>
				<RDCenters number="">
					<RDCenter ID="">
            <technologiesList>
              <technology type="older/current/newer"></technology>
            </technologiesList>
            <funds></funds>
            <costs></costs>
						<delay></delay><!-- le temps minimum accordé apres une découverte (face aux autres joueurs) -->
					</RDCenter>
				</RDCenters>
				<factories number="">
					<factory ID="">
						<maxCapacity>"à remplir</maxCapacity><!-- le stock max qu'elle peut avoir a dispo -->
						<effeciency>"à remplir"</effeciency>
					</factory>
				</factories>
			</entities>
			<mainAccount currency="" fees="" amount=""></mainAccount>
	</Corporation>
	<Corporation  id ="3">
		<name></name>
		<entities number="">
	        <shops number="">
	          <shop location="" ID="">
	            <maxCapacity></maxCapacity>      <!-- la capacité max de stockage qu'elle peut avoir -->
	          </shop>
	        </shops>
				<RDCenters number="">
					<RDCenter ID="">
            <technologiesList>
              <technology type="older/current/newer"></technology>
            </technologiesList>
            <funds></funds>
            <costs></costs>
						<delay></delay><!-- le temps minimum accordé apres une découverte (face aux autres joueurs) -->
					</RDCenter>
				</RDCenters>
				<factories number="">
					<factory ID="">
						<maxCapacity>"à remplir</maxCapacity><!-- le stock max qu'elle peut avoir a dispo -->
						<effeciency>"à remplir"</effeciency>
					</factory>
				</factories>
			</entities>
			<mainAccount currency="" fees="" amount=""></mainAccount>
	</Corporation>
	<Transports type=""></Transports>	

	<Bank>
		<mainAccount currency="$" fees="" amount="100000000000"></mainAccount>
    <!-->		<transaction type="type"> 
			<destination>
				<address>
		            <number>"à remplir"</number>
		            <way type="type">"à remplir""à remplir"</way>
		            <zip_code>"à remplir"</zip_code>
		            <city>"à remplir"</city>
		            <country>"à remplir"</country>
		        </address>
		    </destination>
		    <value>"à remplir"</value>
		    <source>"à remplir"</source> 
		</transaction> <!-->
	</Bank>

	<TimeStamp>
    <maxQuarteur>20</maxQuarteur>
    <delay type="tour"></delay>
	</TimeStamp>
<Global>
	<product id="1">
		<name>X</name>
		<potential>9</potential>
		<refcost id="1">100000</refcost>
		<refcost id="2">1000000</refcost>
		<refcost id="3">10000000</refcost>
		<refcost id="4">100000000</refcost>
		<refcost id="5">200000000</refcost>
		<refcost id="6">400000000</refcost>
		<refcost id="7">600000000</refcost>
		<refcost id="8">800000000</refcost>
		<refcost id="9">1000000000</refcost>
	</product>
	<product id="2">
		<name>Y</name>
		<potential>9</potential>
		<refcost id="1">100000</refcost>
		<refcost id="2">1000000</refcost>
		<refcost id="3">10000000</refcost>
		<refcost id="4">100000000</refcost>
		<refcost id="5">200000000</refcost>
		<refcost id="6">400000000</refcost>
		<refcost id="7">600000000</refcost>
		<refcost id="8">800000000</refcost>
		<refcost id="9">1000000000</refcost>
	</product>
</Global>
</World>

=== EmericJdt/ITtraining/Improved_BigBang/Improved_BigBang.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- le fichier entrée du jeu -->
<!-- il nous faut les balises des différentes classes principales -->
<World xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BigBang.xsd">

	<Region number="" >
		<name></name>
		<demographie>
			<populationNumber></populationNumber>
			<PIB currency=""></PIB>
			<economyPotential currency=""></economyPotential>
		</demographie>
		<macroEventProba>
			<superDepression></superDepression>
			<naturalCatastroph></naturalCatastroph>
			<superGrowth></superGrowth>
		</macroEventProba>
		<entitiesNumber></entitiesNumber>
	</Region>

	<Corporation>
		<name></name>
		<entities number="">
	        <shops number="">
	          <shop location="" ID="">
	            <account currency="" fees="" amount=""></account>
	            <maxCapacity></maxCapacity>      <!-- la capacité max de stockage qu'elle peut avoir -->
	          </shop>
	        </shops>
				<RDCenters number="">
					<RDCenter ID="">
            <technologiesList>
              <technology type="older/current/newer"></technology>
            </technologiesList>
            <funds></funds>
            <costs></costs>
						<delay></delay><!-- le temps minimum accordé apres une découverte (face aux autres joueurs) -->
					</RDCenter>
				</RDCenters>
				<factories number="">
					<factory ID="">
						<maxCapacity>"à remplir</maxCapacity><!-- le stock max qu'elle peut avoir a dispo -->
						<effeciency>"à remplir"</effeciency>
					</factory>
				</factories>
			</entities>
			<mainAccount currency="" fees="" amount=""></mainAccount>
	</Corporation>

	<Transports type=""></Transports>	

	<Bank>
		<mainAccount currency="" fees="" amount=""></mainAccount>
    <!-->		<transaction type="type"> 
			<destination>
				<address>
		            <number>"à remplir"</number>
		            <way type="type">"à remplir""à remplir"</way>
		            <zip_code>"à remplir"</zip_code>
		            <city>"à remplir"</city>
		            <country>"à remplir"</country>
		        </address>
		    </destination>
		    <value>"à remplir"</value>
		    <source>"à remplir"</source> 
		</transaction> <!-->
	</Bank>

	<TimeStamp>
    <maxQuarteur></maxQuarteur>
    <delay type="tour"></delay>
	</TimeStamp>
  <Global>
    <product id="1">
      <name></name>
      <potential>9</potential>
      <refcost id="1">100000</refcost>
      <refcost id="2">1000000</refcost>
      <refcost id="3">10000000</refcost>
      <refcost id="4">100000000</refcost>
      <refcost id="5">200000000</refcost>
      <refcost id="6">400000000</refcost>
      <refcost id="7">600000000</refcost>
      <refcost id="8">800000000</refcost>
      <refcost id="9">1000000000</refcost>
    </product>
    <product id="2">
      <name></name>
      <potential>9</potential>
      <refcost id="1">100000</refcost>
      <refcost id="2">1000000</refcost>
      <refcost id="3">10000000</refcost>
      <refcost id="4">100000000</refcost>
      <refcost id="5">200000000</refcost>
      <refcost id="6">400000000</refcost>
      <refcost id="7">600000000</refcost>
      <refcost id="8">800000000</refcost>
      <refcost id="9">1000000000</refcost>
    </product>
  </Global>

</World>
